### ISSUE TITLE
iceblue and iceblue compact: listitem height to small in autopaging listbox

### ISSUE THREAD

**Issue by yennor** [zkoss/zkThemeTemplate#16]
check out the fiddle:
https://zkfiddle.org/sample/1bt07rq/1-listbox-with-autopaging
if you use iceblue you can see that the listitem is not heigh enough. The combobox gets cut.
When you use iceblue compact you see that the listitem height obviously is too heigh...

the problem seems to be:
.z-listbox-autopaging .z-listcell-content {
    height: 44px;
}
This is the same in both layouts.
if you remove that height style, the height is the expected size

If you use grid instead of listbox, the styling is as expected.

**Comment by cor3000** [comment]
Thanks for reporting this. I transferred this issue to our tracker https://tracker.zkoss.org/browse/ZK-4920 for further investigation/fixing, to set a better default height. (please watch the ticket there)

**about your workaround:**
The autopaging calculations depend on a static height for all listrows in the listbox/grid. 
If you just remove this line you might end up with infinite autopaging calculation loops (causing flickering and unusable UI), in case of varying height of rows.

**better workaround:**
Instead of removing this style, specify a different fixed suitable to your current usage scenario (you need to try out what looks best).
e.g. (if you decide a height of 50px look better)
```
<style>
    .mylist50.z-listbox-autopaging .z-listcell-content {
        height: 50px;
    }
</style>
...
<listbox sclass="mylist50">
...
```
